const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const os = require('node:os')
const { zstdCompressSync } = require('node:zlib')
const { fetchMessageRange, findMessageById, hydrateSearchHits, mergeMessageVariants, resolveOwnedOutputDir } = require('../record-pipeline')
  const { extractLocalFile, searchLocalFiles, isWithinAllowedRoots } = require('../content-tools')
const { validateBaseUrl, renderMcpConfigs } = require('../config')

const rows = Array.from({ length: 12 }, (_, i) => ({ localId: 12 - i, timestamp: 1000 + 12 - i, type: 1, content: `消息 ${12-i}` }))
test('分页中途达到 limit 后，下一页游标不跳过尚未返回的记录', async () => {
  const page = await fetchMessageRange(async ({ limit, offset }) => rows.slice(offset, offset + limit), { limit: 3, page_size: 5 })
  assert.equal(page.pagination.nextOffset, 3)
  const next = await fetchMessageRange(async ({ limit, offset }) => rows.slice(offset, offset + limit), { limit: 3, page_size: 5, offset: page.pagination.nextOffset })
  assert.deepEqual(next.messages.map(m => m.localId), [7, 8, 9])
})
test('重复页必须在有界请求数内停止并标记未完成', async () => {
  let calls = 0
  const page = await fetchMessageRange(async () => { if (++calls > 5) throw new Error('未停止'); return rows.slice(0, 2) }, { limit: 10, page_size: 2 })
  assert.equal(page.pagination.complete, false)
  assert.equal(page.pagination.stopReason, 'no-progress')
})
test('按消息ID精确回查保留长中文和Emoji正文，并返回下一偏移量', async () => {
  const content = '原文🙂中文内容'.repeat(500) + '末尾-marker'
  const source = Array.from({ length: 250 }, (_, index) => ({ localId: 250 - index, timestamp: 1000 - index, content: `synthetic-${index}`, type: 1 }))
  source.push({ localId: 999, timestamp: 1, content, type: 1 })
  const result = await findMessageById(async ({ offset, limit }) => source.slice(offset, offset + limit), { session_id: 'g', local_id: 999, page_size: 50, scan_limit: 500 })
  assert.equal(result.found, true)
  assert.equal(result.message.content, content)
  assert.equal(result.contentIntegrity.characters, Array.from(content).length)
  assert.equal(result.contentIntegrity.utf8Bytes, Buffer.byteLength(content, 'utf8'))
  assert.equal(result.coverage.nextOffset, 251)
})
test('按消息ID精确回查未命中时给出续读范围而非声称全历史不存在', async () => {
  const result = await findMessageById(async ({ offset }) => offset === 0 ? rows.slice(0, 2) : rows.slice(0, 2), { session_id: 'g', local_id: 99, page_size: 2, scan_limit: 6 })
  assert.equal(result.found, false)
  assert.equal(result.partial, true)
  assert.equal(result.coverage.stopReason, 'no-progress')
  assert.equal(result.coverage.nextOffset, 4)
})
test('无效时间范围不能查询', async () => {
  await assert.rejects(fetchMessageRange(async () => [], { start_time: 20, end_time: 10 }), /时间/)
})
test('附件正文搜索超出文件提取预算时标记partial并提供继续读取范围', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'yan-attachment-search-')); t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  const file = path.join(root, 'long.txt'); fs.writeFileSync(file, '甲'.repeat(300) + 'tail-only-marker', 'utf8')
  const result = await searchLocalFiles('tail-only-marker', [root], { max_chars_per_file: 100 })
  assert.equal(result.returned, 0)
  assert.equal(result.complete, false)
  assert.equal(result.partial, true)
  assert.equal(result.truncatedFiles[0].nextOffset, 100)
})
test('附件搜索在单文件预算内跨分块查找，不把尾部关键词当成不存在', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'yan-attachment-continue-')); t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  const file = path.join(root, 'long.txt'); fs.writeFileSync(file, `${'甲'.repeat(250000)}tail-only-marker`, 'utf8')
  const result = await searchLocalFiles('tail-only-marker', [root])
  assert.equal(result.returned, 1)
  assert.equal(result.complete, true)
  assert.equal(result.partial, false)
  assert.equal(result.results[0].matchOffset, 250000)
  assert.match(result.results[0].snippet, /tail-only-marker/)
})
test('附件搜索不会因为20万字符分块边界漏掉横跨边界的关键词', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'yan-attachment-boundary-')); t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  const keyword = 'BOUNDARY'
  const file = path.join(root, 'span.txt'); fs.writeFileSync(file, `${'甲'.repeat(199998)}${keyword}`, 'utf8')
  const result = await searchLocalFiles(keyword, [root])
  assert.equal(result.returned, 1)
  assert.equal(result.partial, false)
  assert.equal(result.results[0].matchOffset, 199998)
})
test('长附件正文可按Unicode安全边界分块读取，不丢中文和Emoji', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'yan-text-chunks-')); t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  const content = '甲🙂乙中文段落'.repeat(40) + '完整结尾-marker'
  const file = path.join(root, 'long.txt'); fs.writeFileSync(file, content, 'utf8')
  const first = await extractLocalFile(file, [root], { max_chars: 37 })
  assert.equal(first.truncated, true); assert.ok(first.nextOffset > 0); assert.equal(first.text + (await extractLocalFile(file, [root], { max_chars: 1000000, offset_chars: first.nextOffset })).text, content)
  assert.equal(first.text.includes('\uFFFD'), false)
})
test('目录 junction 不能让附件读取逃出白名单', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'yan-boundary-'))
  t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  const allowed = path.join(root, 'allowed'), outside = path.join(root, 'outside')
  fs.mkdirSync(allowed); fs.mkdirSync(outside); fs.writeFileSync(path.join(outside, 'private.txt'), 'synthetic private fixture')
  fs.symlinkSync(outside, path.join(allowed, 'link'), process.platform === 'win32' ? 'junction' : 'dir')
  const target = path.join(allowed, 'link', 'private.txt')
  assert.equal(isWithinAllowedRoots(target, [allowed]), false)
  await assert.rejects(extractLocalFile(target, [allowed]), /白名单|allowlisted/)
  assert.equal(resolveOwnedOutputDir('s', path.join(allowed, 'link', 'new'), allowed), null)
})
test('WxLens 的 zstd 十六进制正文会解成原文，坏载荷不会被当成明文', async () => {
  const text = '做一张精细的SVG图片🙂'
  const hex = zstdCompressSync(Buffer.from(text, 'utf8')).toString('hex')
  const source = [{ localId: 7, timestamp: 70, type: 1, senderId: 'person-a', senderName: '我', isSelf: true, content: hex, contentTruncated: false }]
  const found = await findMessageById(async ({ offset, limit }) => source.slice(offset, offset + limit), { session_id: 'filehelper', local_id: 7, page_size: 10, scan_limit: 10 })
  assert.equal(found.found, true)
  assert.equal(found.message.content, text)
  assert.equal(found.message.contentDecoded, 'zstd')
  assert.equal(found.contentIntegrity.contentUndecoded, false)
  assert.equal(found.contentIntegrity.characters, Array.from(text).length)
  const broken = '28b52ffd' + 'ff'.repeat(16)
  const failed = await findMessageById(async () => [{ localId: 8, timestamp: 80, type: 1, content: broken }], { session_id: 'filehelper', local_id: 8 })
  assert.equal(failed.message.content, broken)
  assert.equal(failed.message.contentUndecoded, true)
  assert.equal(failed.contentIntegrity.contentUndecoded, true)
  const bogus = '28b52ffddeadbeef'
  const empty = await findMessageById(async () => [{ localId: 6, timestamp: 60, type: 1, content: bogus }], { session_id: 'filehelper', local_id: 6 })
  assert.equal(empty.message.content, bogus)
  assert.equal(empty.message.contentDecoded, 'zstd-empty')
})
test('上游截断的zstd正文不能被精确回查标为完整', async () => {
  const text = '长正文🙂'.repeat(900)
  const hex = zstdCompressSync(Buffer.from(text, 'utf8')).toString('hex')
  const truncated = { localId: 10, timestamp: 100, type: 1, content: hex.slice(0, 2000), truncated: true, originalLength: hex.length }
  const found = await findMessageById(async () => [truncated], { session_id: 'g', local_id: 10 })
  assert.equal(found.found, true)
  assert.equal(found.partial, true)
  assert.equal(found.contentIntegrity.sourceReportedTruncated, true)
  assert.equal(found.contentIntegrity.complete, false)
})
test('搜索完整明文优先于被WxLens截断的精确zstd字段，同时回填身份和类型', async () => {
  const text = '长正文🙂'.repeat(900)
  const hex = zstdCompressSync(Buffer.from(text, 'utf8')).toString('hex')
  const hit = { localId: 11, timestamp: 110, sessionId: 'g', type: 0, senderId: '', content: text, contentSource: 'search-index' }
  const direct = { localId: 11, timestamp: 110, type: 1, senderId: 'wxid_person', senderName: '本人', isSelf: true, isSend: 1, content: hex.slice(0, 2000), truncated: true, originalLength: hex.length }
  const merged = await hydrateSearchHits(async () => [direct], [hit], { session_id: 'g', scan_limit: 10 })
  assert.equal(merged[0].content, text)
  assert.equal(merged[0].senderId, 'wxid_person')
  assert.equal(merged[0].type, 1)
  assert.equal(merged[0].contentSource, 'search-index')
  assert.equal(merged[0].contentIntegrity.complete, true)
  assert.equal(merged[0].identityComplete, true)
})
test('搜索命中缺少会话字段时使用调用参数回填', async () => {
  const hit = { localId: 9, type: 1, senderId: 'p', content: '正文' }
  const hydrated = await hydrateSearchHits(null, [hit], { session_id: 'fallback-session' })
  assert.equal(hydrated[0].sessionId, 'fallback-session')
  assert.equal(hydrated[0].contentComplete, true)
})
test('搜索回填受扫描预算约束并显式报告未恢复身份', async () => {
  const hit = { localId: 3000, sessionId: 'g', type: 0, content: '索引正文' }
  const hydrated = await hydrateSearchHits(async ({ limit, offset }) => ({ messages: Array.from({ length: limit }, (_, index) => ({ localId: offset + limit - index, type: 1, senderId: 'p', content: '其他消息' })) }), [hit], { scan_limit: 3 })
  assert.equal(hydrated[0].hydrationStatus.complete, false)
  assert.equal(hydrated[0].hydrationStatus.stopReason, 'scan-limit')
  assert.equal(hydrated[0].hydrationStatus.nextOffset, 3)
  assert.equal(hydrated[0].identityComplete, false)
})
test('搜索命中即使不需回填也带正文完整性状态', async () => {
  const hits = await hydrateSearchHits(null, [{ localId: 12, sessionId: 'g', type: 1, senderId: 'person', content: '普通正文' }])
  assert.equal(hits[0].contentComplete, true)
  assert.equal(hits[0].contentSource, 'search-index')
})
test('正文搜索把不可用解析器列为未覆盖，不把它当成完整未命中', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'yan-attachment-unsupported-')); t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  fs.writeFileSync(path.join(root, 'image.dat'), Buffer.from([1, 2, 3, 4]))
  const result = await searchLocalFiles('never-present', [root])
  assert.equal(result.candidates, 1)
  assert.equal(result.returned, 0)
  assert.equal(result.complete, false)
  assert.equal(result.partial, true)
  assert.equal(result.failures[0].parseSupport, 'unsupported')
})
test('附件正文搜索不因为文件名不含关键词而跳过文件', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'yan-attachment-name-')); t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  fs.writeFileSync(path.join(root, 'table.csv'), '类型,键能\n氢键,20\n', 'utf8')
  const result = await searchLocalFiles('氢键', [root], { keyword: '氢键' })
  assert.equal(result.candidates, 1)
  assert.equal(result.returned, 1)
  assert.match(result.results[0].snippet, /氢键/)
})
test('本机地址与客户端配置', () => {
  assert.equal(validateBaseUrl('http://127.0.0.1:5032/'), 'http://127.0.0.1:5032')
  for (const value of ['https://example.com', 'http://127.0.0.1:5032/x', 'http://localhost:5032', 'http://user:pass@127.0.0.1']) assert.throws(() => validateBaseUrl(value))
  const configs = renderMcpConfigs()
  assert.equal(JSON.parse(configs.json).mcpServers.yan.args.length, 1)
  assert.match(configs.codex, /\[mcp_servers\.yan\]/)
})
