const {z}=require('zod')
const {createArticleStore,extractArticleLinks,filterArticleHistory}=require('./wechat-articles')
const {imageContent,readLocalImage,imageInfo}=require('./image-content')
const {searchTencent}=require('./tencent-search')
const {searchArticles,searchArticlesBatch}=require('./article-search')
const {createCandidateStore}=require('./article-candidates')
const {fetchMessageRange}=require('./record-pipeline')
function registerArticles({register,result,failure,request,accountContext,store=createArticleStore(),candidateStore=createCandidateStore()}) {
 const id=z.string().regex(/^[a-f0-9]{64}$/),url=z.string().max(4096),time=z.number().int().nonnegative().optional()
 const safe=fn=>async p=>{try{return await fn(p)}catch(e){return failure(e)}}
 const saveHits=(hits,run)=>candidateStore.upsert(hits,{run})
 register('search_wechat_articles','通过搜狗公开微信索引发现文章候选，可按账号名称与搜索索引时间过滤；结果写入可恢复账本。不保证完整历史。',{query:z.string().min(1).max(200),page:z.number().int().min(1).max(10).optional(),account_name:z.string().min(1).max(200).optional(),start_time:time,end_time:time},safe(async p=>{const r=await searchArticles(p);return result({...r,candidateLedger:saveHits(r.results,{queries:[p.query],stopReason:null,partial:false,remaining:r.nextPage?[{query:p.query,page:r.nextPage,reason:'next_page'}]:[]})})}))
 register('search_wechat_articles_batch','高强度多轮发现公众号文章：请求间隔1.2秒、最多12次/45秒；验证码或429/403终止整个批次；候选写入可恢复账本。不保证完整历史。',{account_name:z.string().min(1).max(200).optional(),query:z.string().min(1).max(200).optional(),queries:z.array(z.string().min(1).max(200)).max(5).optional(),max_pages:z.number().int().min(1).max(10).optional(),days:z.never().optional().describe('不支持days，请用Unix秒start_time/end_time过滤索引结果'),start_time:time,end_time:time},safe(async p=>{const r=await searchArticlesBatch(p);return result({...r,candidateLedger:saveHits(r.results,{queries:r.coverage.queries,requests:r.coverage.requests,stopReason:r.stopReason,partial:r.partial,remaining:r.remaining})})}))
 register('search_wechat_articles_tencent','可选腾讯云WSA官方搜索：限定微信公众号域名和最近N天。需本人预先启用与安全配置凭据，可能收费；结果写入候选账本，不保证全量历史。',{query:z.string().min(1).max(200),days:z.number().int().min(1).max(30).optional()},safe(async p=>{const r=await searchTencent(p);return result({...r,candidateLedger:saveHits(r.results,{queries:[p.query],stopReason:null,partial:r.failures?.length>0,remaining:[]})})}))
 register('fetch_wechat_article','联网读取公众号文章正文、配图清单与发布时间。遇验证/登录停止。可提供candidate_id：按账号名核验候选，不一致标为conflicting。',{url,candidate_id:id.optional()},safe(async p=>{const a=await store.fetchArticle(p);return result(p.candidate_id?{...a,candidate:candidateStore.verify(p.candidate_id,a)}:a)}))
 register('import_wechat_article','导入本人或AI浏览器已正常打开的文章HTML；不执行脚本、不索取Cookie。可提供candidate_id完成候选核验。',{url,html:z.string().min(1).max(4*1024*1024),partial:z.boolean().optional(),candidate_id:id.optional()},safe(async p=>{const a=await store.importHtml(p);return result(p.candidate_id?{...a,candidate:candidateStore.verify(p.candidate_id,a)}:a)}))
 register('get_saved_article','读取本机文章库中的一篇正文和配图清单。',{article_id:id},safe(async p=>result(store.get(p.article_id))))
 register('list_article_candidates','读取公众号候选账本。candidate不是原文核验；verified只表示本地核验通过，不是完整历史。',{status:z.enum(['candidate','verified','conflicting','unknown']).optional(),limit:z.number().int().min(1).max(500).optional()},safe(async p=>result(candidateStore.list(p))))
 register('update_article_candidate','人工更新候选状态。只有已经通过正常浏览器或文章工具核对后才应标记verified。',{candidate_id:id,status:z.enum(['candidate','verified','conflicting','unknown']),article_url:url.optional(),account_name:z.string().max(200).optional(),published_at:z.string().max(100).optional(),reason:z.string().max(500).optional()},safe(async p=>result(candidateStore.update(p.candidate_id,{status:p.status,articleUrl:p.article_url,accountName:p.account_name,publishedAt:p.published_at,reason:p.reason}))))
 register('read_article_image','读取已存档公众号文章的一张配图，返回原生MCP image块。每次一张，最多4MiB。',{article_id:id,image_index:z.number().int().min(1).max(100)},safe(async p=>{const r=await store.image(p.article_id,p.image_index);return {content:[...result({...r.source,...r.info}).content,imageContent(r.buffer)]}}))
 register('download_article_images','下载已存档公众号文章配图到本机output/articles独占目录；返回逐图结果、SHA256和缺失范围，默认前12张。',{article_id:id,image_indices:z.array(z.number().int().min(1).max(100)).min(1).max(20).optional()},safe(async p=>result(await store.download(p.article_id,p.image_indices))))
 register('read_wechat_image','读取明确选定的本机微信标准图片，返回原生MCP image。加密DAT不解密，路径不证明会话归属。',{source_path:z.string().min(1).max(4096)},safe(async p=>{const {roots}=accountContext(),b=readLocalImage(p.source_path,roots);return {content:[...result({...imageInfo(b),boundary:'文件由调用方明确选定，未验证与特定聊天消息的归属。'}).content,imageContent(b)]}}))
 register('list_shared_articles','在指定会话有界分页扫描公众号文章链接，按URL去重并保留每条聊天引用；筛选时间是分享时间，不能当成文章发布时间。',{session_ids:z.array(z.string().min(1)).min(1).max(10),scan_limit:z.number().int().min(1).max(1000).optional(),offset:z.number().int().nonnegative().optional(),start_time:time,end_time:time},safe(async p=>{
  const messages=[],sessions=[]
  for(const session_id of [...new Set(p.session_ids)]){try{const page=await fetchMessageRange(params=>request('/api/messages',params),{session_id,limit:p.scan_limit||200,scan_limit:p.scan_limit||200,offset:p.offset,start_time:p.start_time,end_time:p.end_time});messages.push(...page.messages.map(m=>({...m,sessionId:session_id})));sessions.push({sessionId:session_id,pagination:page.pagination})}catch(e){sessions.push({sessionId:session_id,error:e.message})}}
  const links=extractArticleLinks(messages)
  return result({links,sessions,scannedMessages:messages.length,partial:sessions.some(s=>s.error||s.pagination?.hasMore||s.pagination?.complete===false),boundary:'仅覆盖指定会话与本次分页窗口，可能遗漏未暴露URL的分享卡片。用返回offset继续读取；再对URL调用fetch_wechat_article，不自动联网批量抓取。'})
 }))
 register('query_article_history','按公众号biz（优先）或名称、文章发布时间筛选本机已获取文章。仅为已收集历史，不是完整公众号历史。',{account_biz:z.string().min(1).max(300).optional(),account_name:z.string().min(1).max(200).optional(),identity_status:z.enum(['verified','candidate','unknown']).optional(),start_time:time,end_time:time},safe(async p=>{const local=store.list(),history=filterArticleHistory(local.articles,p);return result({...history,articles:history.articles.map(({id,url,title,account,publishedAt,identityStatus,coverage})=>({id,url,title,account,publishedAt,identityStatus,coverage})),undated:history.undated.map(({id,url,title,account,identityStatus})=>({id,url,title,account,identityStatus})),libraryTruncated:local.truncated,failures:local.failures||[]})}))
}
module.exports={registerArticles}
